#!/usr/bin/env bash
# Verify that the vendored crypto conformance corpus is byte-identical to the
# spec source at the ref pinned in .spec-ref. Local mirror of the CI gate — the
# crypto-corpus twin of scripts/check-schemas.sh.
#
# Vendored files (tests/crypto/fixtures/) <- spec source:
#   ble-handshake-keyschedule.json  <-  conformance/test-vectors/crypto/
#   rfc-primitive-anchors.json      <-  conformance/test-vectors/crypto/
#   canonical-form.json             <-  conformance/test-vectors/crypto/
#   server-test-pub.pem             <-  conformance/test-keys/
#
# canonical-form.json is why this script stopped being optional. Until 0.14.0 it
# was never invoked by CI at all, and the canonical-form vectors lived as two
# hand-maintained copies — one per SDK — whose agreement was asserted in a
# comment and by nothing else. Both SDKs could be edited into agreeing with each
# other and disagreeing with the spec, which is the shape of every defect this
# release fixes. The vectors are now vendored from one upstream and this gate is
# what makes "vendored" mean something.
#
# Usage:
#   scripts/check-crypto-vectors.sh                       # clones spec at .spec-ref
#   SPEC_REPO=/local/path scripts/check-crypto-vectors.sh # diffs a local checkout
#
# Exit: 0 if byte-identical, 1 otherwise.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC_REF="$(tr -d '[:space:]' < "${REPO_ROOT}/.spec-ref")"
FIXTURES="${REPO_ROOT}/tests/crypto/fixtures"

if [[ -n "${SPEC_REPO:-}" ]]; then
  SPEC_SRC="${SPEC_REPO}"
  echo "Comparing against local spec checkout at ${SPEC_REPO} (.spec-ref=${SPEC_REF} — not enforced for local mode)"
else
  TMPDIR="$(mktemp -d)"
  trap 'rm -rf "${TMPDIR}"' EXIT
  echo "Cloning ospp-org/spec at ${SPEC_REF}..."
  git clone --quiet --depth 1 --branch "${SPEC_REF}" https://github.com/ospp-org/spec.git "${TMPDIR}/spec"
  SPEC_SRC="${TMPDIR}/spec"
fi

CRYPTO_SRC="${SPEC_SRC}/conformance/test-vectors/crypto"
KEYS_SRC="${SPEC_SRC}/conformance/test-keys"
# The shipped corpus carries some vectors instead of tests/crypto/fixtures/ —
# tamper-rejection.json is vendored there. The completeness arm below counts a
# vector as present if it sits in EITHER root, so that a file vendored to the
# published corpus is not reported as absent.
CORPUS_CRYPTO="${REPO_ROOT}/src/test-vectors/crypto"

if [[ ! -d "${CRYPTO_SRC}" ]]; then
  echo "ERROR: ${CRYPTO_SRC} not found — the BLE crypto corpus exists only in spec >= v0.6.0." >&2
  echo "       Bump .spec-ref to a v0.6.0+ tag (and push that tag to ospp-org/spec), or run in" >&2
  echo "       local mode: SPEC_REPO=/path/to/spec scripts/check-crypto-vectors.sh" >&2
  exit 1
fi

status=0
check() {
  local src="$1" dst="$2" name="$3"
  if [[ ! -f "${src}" ]]; then echo "DRIFT: missing in spec source: ${name}" >&2; status=1; return; fi
  if [[ ! -f "${dst}" ]]; then echo "DRIFT: missing vendored copy: ${name}" >&2; status=1; return; fi
  if cmp -s "${src}" "${dst}"; then
    echo "OK identical: ${name}"
  else
    echo "DRIFT: ${name} differs from spec ${SPEC_REF}" >&2
    status=1
  fi
}

# DRIVEN BY WHAT IS VENDORED, NOT BY A HARDCODED LIST. CONVERTED 2026-09-09.
#
# This was four `check` lines naming four files. An INCLUSION list fails silently
# in exactly one direction: vendor a fifth file and nothing compares it, so it can
# drift from the spec forever while this script prints "OK — vendored crypto
# corpus byte-identical". `tamper-rejection.json` is the standing proof — it is
# vendored in this repo (under src/test-vectors/crypto/) and these four lines
# never mentioned it. ospp-sdk-php made this same conversion at 0.27.0; this
# repo did not, and the two gates have been asymmetric since.
#
# SDK-LOCAL fixtures: authored here, with no upstream counterpart. The value is
# the REASON, not the name — a later reader has to be able to disagree with it
# rather than take it on trust. Anything NOT listed here is expected to exist in
# the spec, which is what makes a newly vendored file compared by default instead
# of ignored by default.
declare -A SDK_LOCAL=(
  [canonical-mac-strip.json]='authored here — pins that computeMac strips `mac` before canonicalising, a library-side property with no spec vector'
  [hmac-golden-vectors.json]='authored here — HMAC goldens for this SDK, generated by tests/crypto/fixtures/generators'
  [signing-classification.json]='authored here — which actions this SDK signs, a library policy rather than a protocol fact'
)

vendored=0
while IFS= read -r dst; do
  name="$(basename "${dst}")"
  if [[ -v "SDK_LOCAL[${name}]" ]]; then
    echo "SKIP local:   ${name} — ${SDK_LOCAL[${name}]}"
    continue
  fi
  case "${name}" in
    *.json) check "${CRYPTO_SRC}/${name}" "${dst}" "${name}" ;;
    *.pem)  check "${KEYS_SRC}/${name}"   "${dst}" "${name}" ;;
    *)      echo "DRIFT: ${name} is vendored here but is neither a vector nor a key" >&2; status=1 ;;
  esac
  vendored=$((vendored + 1))
done < <(find "${FIXTURES}" "${CORPUS_CRYPTO}" -maxdepth 1 -type f \( -name '*.json' -o -name '*.pem' \) 2>/dev/null | sort)

if [[ "${vendored}" -lt 4 ]]; then
  echo "DRIFT: only ${vendored} vendored crypto artefact(s) found — a loop over an empty or" >&2
  echo "       truncated directory reports success for zero work. Expected at least 4." >&2
  status=1
fi

# COMPLETENESS — the direction a vendored-side walk cannot see. ADDED 2026-09-09.
#
# Iterating the vendored directory proves "everything we vendored matches the
# spec". It cannot prove "we vendored everything the spec has", because a spec
# vector that was never copied is never walked and so is never missed.
#
# MEASURED, not argued. On 2026-09-09 the spec carried FIVE crypto vectors and
# this SDK held FOUR: `mqtt-mac.json` had never been vendored, in either SDK, and
# both gates were green. It is the vector that pins §5.4 — the DECODED-key rule —
# and it is the one an integrator needs to verify envelope signing before going
# near the wire. `canonical-mac-strip.json` in this very directory quotes a mac
# value out of it BY HAND, so the corpus already depended on a file it did not
# carry.
#
# SPEC_ONLY is the counterpart of SDK_LOCAL and carries the same obligation — a
# REASON, not a bare name. Empty today.
declare -A SPEC_ONLY=()

spec_side=0
while IFS= read -r src; do
  name="$(basename "${src}")"
  spec_side=$((spec_side + 1))
  if [[ -v "SPEC_ONLY[${name}]" ]]; then
    echo "SKIP spec-only: ${name} — ${SPEC_ONLY[${name}]}"
    continue
  fi
  # A vector may be vendored either beside the fixtures or under the shipped
  # corpus (tamper-rejection.json lives there), so both roots count as vendored.
  if [[ ! -f "${FIXTURES}/${name}" && ! -f "${CORPUS_CRYPTO}/${name}" ]]; then
    echo "DRIFT: ${name} exists in spec ${SPEC_REF} but was NEVER vendored here." >&2
    echo "       Not drift in a copy — an absent copy. Add it to ${FIXTURES}/, or" >&2
    echo "       add it to SPEC_ONLY with the reason it does not belong in this SDK." >&2
    status=1
  fi
done < <(find "${CRYPTO_SRC}" -maxdepth 1 -type f -name '*.json' | sort)

if [[ "${spec_side}" -lt 4 ]]; then
  echo "DRIFT: the spec crypto directory yielded only ${spec_side} vector(s) — the" >&2
  echo "       completeness walk found nothing to check. Expected at least 4." >&2
  status=1
fi

if [[ "${status}" -eq 0 ]]; then
  echo "OK — vendored crypto corpus byte-identical to spec ${SPEC_REF}"
else
  echo "" >&2
  echo "Fix: re-vendor from spec conformance/test-vectors/crypto/ + test-keys/server-test-pub.pem" >&2
  echo "into tests/crypto/fixtures/ (cp) and re-commit. Do not edit vendored vectors in place." >&2
fi
exit "${status}"
